apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # ArgoCD core installation (from upstream)
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.2/manifests/install.yaml

patches:
  # Strategic merge patches for existing resources in upstream manifest
  - path: argocd-cm.yaml
  - path: argocd-cmd-params.yaml
  - path: argocd-rbac.yaml
  # JSON patches below
  # Make ArgoCD accessible via NodePort for local/k3d environments
  - patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30443
    target:
      kind: Service
      name: argocd-server
      namespace: argocd

  # Reduce resource requests for local environments
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
    target:
      kind: Deployment
      namespace: argocd

# Note: Do NOT add app.kubernetes.io/part-of labels here as ArgoCD
# components look for resources with app.kubernetes.io/part-of=argocd
