apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - network-policies.yaml
  - fastapi/deployment.yaml
  - fastapi/service.yaml
  - fastapi/hpa.yaml
  - fastapi/pdb.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: k3s-platform
    includeSelectors: false